fix: display jsc error messages instead of just returning an exit code when it fails  + change order of arguments in diff, so updates are displayed at the bottom (=> more visible)
example, if we don't include data/naf.js:

            < ]
            ---
            > Exception: ReferenceError: Can't find variable: naf
            > map@../reduce.algo2/map.js:72:46
            > ../reduce.algo2/map_test.js:27:60
            > forEach@[native code]
            > runMongoMap@../reduce.algo2/map_test.js:27:19
            > global code@../reduce.algo2/map_test.js:38:33
            If this diff was expected, update the golden file on server by running ./test_map_reduce_algo2.sh --update
            Cleaned up temp directory