fix Uncaught exception in reduce.algo2/algo2_golden_tests.ts
  reduce.algo2/apart.ts(27,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(38,25): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(39,25): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(65,5): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(66,7): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(68,5): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(69,7): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(75,7): error TS2322: Type 'SortieAPart | {}' is not assignable to type 'SortieAPart'.
    Type '{}' is missing the following properties from type 'SortieAPart': apart_heures_autorisees, apart_heures_consommees, apart_motif_recours, apart_heures_consommees_cumulees
  reduce.algo2/apart.ts(76,7): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(76,52): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(83,9): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(84,7): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(84,13): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(89,9): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(90,7): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(92,21): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(92,52): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(95,24): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(96,11): error TS2322: Type 'SortieAPart | {}' is not assignable to type 'SortieAPart'.
    Type '{}' is missing the following properties from type 'SortieAPart': apart_heures_autorisees, apart_heures_consommees, apart_motif_recours, apart_heures_consommees_cumulees
  reduce.algo2/apart.ts(97,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(98,14): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(99,13): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(100,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(101,13): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(101,23): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(106,9): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(107,9): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(113,24): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/apart.ts(114,9): error TS2532: Object is possibly 'undefined'.