fix Uncaught exception in reduce.algo2/algo2_golden_tests.ts
  reduce.algo2/effectifs.ts(42,19): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/effectifs.ts(42,49): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/effectifs.ts(49,14): error TS2769: No overload matches this call.
    Overload 1 of 4, '(value: string | number | Date): Date', gave the following error.
      Argument of type 'number | undefined' is not assignable to parameter of type 'string | number | Date'.
        Type 'undefined' is not assignable to type 'string | number | Date'.
    Overload 2 of 4, '(value: string | number): Date', gave the following error.
      Argument of type 'number | undefined' is not assignable to parameter of type 'string | number'.
        Type 'undefined' is not assignable to type 'string | number'.
  reduce.algo2/effectifs.ts(56,5): error TS2322: Type '{ effectif?: number | null; effectif_ent?: number | null; effectif_ent_reporte?: 0 | 1; effectif_reporte?: 0 | 1; effectif_past_6?: number; effectif_past_12?: number; effectif_past_18?: number; ... 4 more ...; effectif_ent_past_24?: number; }' is not assignable to type 'SortieEffectifs'.
    Type '{ effectif?: number | null; effectif_ent?: number | null; effectif_ent_reporte?: 0 | 1; effectif_reporte?: 0 | 1; effectif_past_6?: number; effectif_past_12?: number; effectif_past_18?: number; ... 4 more ...; effectif_ent_past_24?: number; }' is not assignable to type 'Record<CléSortieEffectif, number | null>'.
      Property 'effectif' is optional in type '{ effectif?: number | null; effectif_ent?: number | null; effectif_ent_reporte?: 0 | 1; effectif_reporte?: 0 | 1; effectif_past_6?: number; effectif_past_12?: number; effectif_past_18?: number; ... 4 more ...; effectif_ent_past_24?: number; }' but required in type 'Record<CléSortieEffectif, number | null>'.
  reduce.algo2/effectifs.ts(79,7): error TS2322: Type '{ effectif?: number | null; effectif_ent?: number | null; effectif_ent_reporte?: 0 | 1; effectif_reporte?: 0 | 1; effectif_past_6?: number; effectif_past_12?: number; effectif_past_18?: number; ... 4 more ...; effectif_ent_past_24?: number; }' is not assignable to type 'SortieEffectifs'.
    Type '{ effectif?: number | null; effectif_ent?: number | null; effectif_ent_reporte?: 0 | 1; effectif_reporte?: 0 | 1; effectif_past_6?: number; effectif_past_12?: number; effectif_past_18?: number; ... 4 more ...; effectif_ent_past_24?: number; }' is not assignable to type 'Record<CléSortieEffectif, number | null>'.
      Property 'effectif' is optional in type '{ effectif?: number | null; effectif_ent?: number | null; effectif_ent_reporte?: 0 | 1; effectif_reporte?: 0 | 1; effectif_past_6?: number; effectif_past_12?: number; effectif_past_18?: number; ... 4 more ...; effectif_ent_past_24?: number; }' but required in type 'Record<CléSortieEffectif, number | null>'.