fix Uncaught exception in compact/ava_tests.ts
  test/helpers/mongodb.ts(35,5): error TS2532: Object is possibly 'undefined'.
  test/helpers/mongodb.ts(79,30): error TS2322: Type '{ key: K; values: V[]; } | { _id: K; values: never[]; }' is not assignable to type '{ key: K; values: V[]; }'.
    Type '{ _id: K; values: never[]; }' is not assignable to type '{ key: K; values: V[]; }'.
      Object literal may only specify known properties, and '_id' does not exist in type '{ key: K; values: V[]; }'.
  test/helpers/mongodb.ts(80,5): error TS2532: Object is possibly 'undefined'.