Uncaught exception in reduce.algo2/algo2_golden_tests.ts
  reduce.algo2/cotisationsdettes.ts(66,7): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(67,7): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(72,17): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(84,19): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(85,17): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(86,21): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(87,20): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(92,28): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(93,26): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(101,5): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(102,15): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(103,5): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(105,9): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(105,40): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(105,40): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(118,34): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(123,29): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(124,37): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(129,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(130,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(136,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(137,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(146,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(147,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(153,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(154,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(167,20): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(168,26): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(169,27): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(184,5): error TS2322: Type 'SortieCotisationsDettes | {}' is not assignable to type 'SortieCotisationsDettes'.
    Type '{}' is not assignable to type 'SortieCotisationsDettes'.
      Type '{}' is missing the following properties from type '{ interessante_urssaf: boolean; cotisation: number; montant_part_ouvriere: number; montant_part_patronale: number; }': interessante_urssaf, cotisation, montant_part_ouvriere, montant_part_patronale
  reduce.algo2/cotisationsdettes.ts(189,7): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(189,24): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(214,7): error TS2322: Type '{ interessante_urssaf?: boolean; cotisation?: number; montant_part_ouvriere?: number; montant_part_patronale?: number; montant_part_ouvriere_past_1?: number; montant_part_ouvriere_past_2?: number; ... 7 more ...; montant_part_patronale_past_12?: number; }' is not assignable to type 'SortieCotisationsDettes'.
    Type '{ interessante_urssaf?: boolean; cotisation?: number; montant_part_ouvriere?: number; montant_part_patronale?: number; montant_part_ouvriere_past_1?: number; montant_part_ouvriere_past_2?: number; ... 7 more ...; montant_part_patronale_past_12?: number; }' is not assignable to type '{ interessante_urssaf: boolean; cotisation: number; montant_part_ouvriere: number; montant_part_patronale: number; }'.
      Property 'interessante_urssaf' is optional in type '{ interessante_urssaf?: boolean; cotisation?: number; montant_part_ouvriere?: number; montant_part_patronale?: number; montant_part_ouvriere_past_1?: number; montant_part_ouvriere_past_2?: number; ... 7 more ...; montant_part_patronale_past_12?: number; }' but required in type '{ interessante_urssaf: boolean; cotisation: number; montant_part_ouvriere: number; montant_part_patronale: number; }'.
  reduce.algo2/cotisationsdettes.ts(216,51): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(217,52): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisationsdettes.ts(229,9): error TS2322: Type '{ interessante_urssaf: false; cotisation?: number; montant_part_ouvriere?: number; montant_part_patronale?: number; montant_part_ouvriere_past_1?: number; montant_part_ouvriere_past_2?: number; ... 7 more ...; montant_part_patronale_past_12?: number; }' is not assignable to type 'SortieCotisationsDettes'.
    Type '{ interessante_urssaf: false; cotisation?: number; montant_part_ouvriere?: number; montant_part_patronale?: number; montant_part_ouvriere_past_1?: number; montant_part_ouvriere_past_2?: number; ... 7 more ...; montant_part_patronale_past_12?: number; }' is not assignable to type '{ interessante_urssaf: boolean; cotisation: number; montant_part_ouvriere: number; montant_part_patronale: number; }'.
      Property 'cotisation' is optional in type '{ interessante_urssaf: false; cotisation?: number; montant_part_ouvriere?: number; montant_part_patronale?: number; montant_part_ouvriere_past_1?: number; montant_part_ouvriere_past_2?: number; ... 7 more ...; montant_part_patronale_past_12?: number; }' but required in type '{ interessante_urssaf: boolean; cotisation: number; montant_part_ouvriere: number; montant_part_patronale: number; }'.