feat(JS): Conversion de "compact" en TypeScript + support de ES2016 (#56)
Problème: Pierre m'a fait savoir que les problèmes les plus couteux qui étaient survenus lors de l'exécution des calculs étaient liés à:
- des erreurs de type des variables et paramètres passés aux fonctions JS, ex: `Delai` (défini dans `lib/urssaf/delai.go` et `delais.ts`), notamment quand elles portent des données venant de la DB
- l'absence occasionnelle de certaines propriété, ex: l'évaluation de `v.delai.montant_echeancier` cause une erreur si `delai` est `undefined`

Solution proposée: accélérer la migration vers TypeScript, pour prévenir ces erreurs grâce à l'analyse statique des types par leur explicitation.

Cette PR contribue à cette solution, en:
- convertissant tous les fichiers JS de `compact` au format TypeScript (c'est une première étape)
- et en affinant la configuration de TypeScript et la déclaration de variables globales, de manière à ce que la conversion fonctionne.

Détail des changements + notes:
- J'ai renommé les fichiers JS pour qu'ils aient l'extension TS. => Le diff de cette PR est moins grave qu'il n'y parait car le formatage automatique fait que `git` ne les reconnait pas comme leur égal.
- J'ai fait de mon mieux pour respecter les recommandations de TypeScript, ESLint et Codacy lors de la conversion => j'ai commenté les modifications correspondantes dans cette PR.
- J'ai spécifié ES2016 comme version du langage JavaScript (en sortie de transpilation TypeScript), comme requis par l'usage de la fonction `[].includes()` dans une des fonctions de `compact`. (à noter que ES6/ES2015 est supporté par MongoDB [à partir de la version 3.2](cf https://docs.mongodb.com/manual/release-notes/3.2-javascript/#modernized-javascript-implementation-es6), et que nous utilisons la version 4.x en production)
- Je n'ai pas constaté d'impact du passage en ES2016 sur la performance de transpilation, de linting et d'exécution des tests.

```sh
$ time (go test && cd js && npm run lint && npm test)
```

Pour exécuter des tests exhaustifs:

```sh
(cd dbmongo && go generate ./...) && \
(cd dbmongo/js && npm test) && \
(cd dbmongo && go test) && \
(cd dbmongo && killall dbmongo; go build) && \
./test-api.sh
```

* feat(JS): Support de ES6/ES2015 dans les fonctions JS exécutées par MongoDB 3.2
cf https://docs.mongodb.com/manual/release-notes/3.2-javascript/#modernized-javascript-implementation-es6

* target=es3 => pas de différence

* target=es5 => légère différence dans la manière d'exporter les fonctions transpilées
... mais aucun impact sur durée de transpilation, linting et tests

* docs: mentionner MongoDB 4.0 comme prérequis
suite à concertation avec l'équipe, et vérification de la version employée en production
note: ES6/ES2015 est supporté depuis MongoDB 3.2, cf https://docs.mongodb.com/manual/release-notes/3.2-javascript/#modernized-javascript-implementation-es6

* fix: exclude `Object.defineProperty(exports.` headers

* fix `go test` error: `add_test: Exception: SyntaxError: Unexpected keyword 'export'`
by removing the "export" prefix from function defs

* try converting map.js to ts

* regroupement des déclarations globales de MongoDB et JSC

* fix security of glob file matchers, cf https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/file/44984125926/issues/source?bid=18037842&fileBranchId=18232344#l4

* convert "compact" JS files to TS + fix errors

* fix: add required globals

* fix(TS): switch to es2016, because [].includes() is being used

* go generate

* fix: prevent trailing new lines in js files, while debugging tests

* fix(codacy): utilisation d'(in)égalité strict, quand possible

* fix(codacy): fix "is not defined" warnings

* fix(codacy): fix "is not defined" warnings

* fix: prevent "import" statements in JS files (not supported by JSC)

* fix: go generate

* added types in complete_reporder() => fixed lint issues

* wip: warnings sur les types dans currentState.js

* ✅ types return of currentState

* 🔵 moved shared types to globals

* 🔵 also moved complete_reporder's types to globals.ts

* 🔵 reworked CurrentDataState type + added comments

* green: return type in finalize.ts

* Refacto: commentaire + TODO dans finalize.ts

* lint fix

* fix: return type of map() + TODO

* fix: go generate

* specification de type de `this` dans `map()`
note: le paramètre est consommé par TypeScript => il n'apparait plus une fois le code transpilé en JS pour MongoDB (jsFunctions.go)

* fix: let compact::map() throw in case of error

* fix "error TS2304: Cannot find name 'serie_periode'." on `npm run test:coverage`
cf https://github.com/TypeStrong/ts-node#help-my-types-are-missing

* clean-up: stop displaying filenames when transpiling

* 🔴 activate TS' strict null checks

* complete return type of fraisFinancier()

* naive fixes to satisfy strictNullChecks

* Correction type test ava dans delai_test.ts

* 🔵 RawDataValues-->CompanyDataValues parce que reduce() est sensé retourner le même type que ce qu'il reçoit en entrée

* 🔵 specification du type de retour de reduce() + ajout d'explications en commentaires

* Intégration de nouveaux types dans les paramètres

Séparation CompanyDataValues et CompanyDataValuesWithFlags

* remplacé type any[] par BatchValue[]

* Import des fonctions (f.*) depuis les fichiers .ts

* refacto: Linting

* fix: Chemins relatifs dans les imports (pour nyc)

Co-authored-by: Pierre Camilleri <pierre.camilleri@direccte.gouv.fr>