Uncaught exception in reduce.algo2/algo2_golden_tests.ts
  reduce.algo2/finalize.ts(49,15): error TS2339: Property 'effectif' does not exist on type 'Partial<DonnéesAgrégées> | undefined'.
  reduce.algo2/finalize.ts(53,15): error TS2339: Property 'apart_heures_consommees' does not exist on type 'Partial<DonnéesAgrégées> | undefined'.
  reduce.algo2/finalize.ts(59,9): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/finalize.ts(60,9): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/finalize.ts(64,12): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/finalize.ts(65,12): error TS2532: Object is possibly 'undefined'.