✅ fix: diff bizare de `exercice_bdf` dans les tests d'intégration de `map` et `finalize`:
  ```
  --- FAIL: Test_js (9.97s)
    --- FAIL: Test_js/test_finalize_algo2.sh (5.01s)
        js_test.go:67: Error status: 1
            stderr:
            stdout: Test failed, because of diff: 3616c3616
            <       "exercice_bdf": 2013,
            ---
            >       "exercice_bdf": 2014,
  ```

=> tous les tests d'intégration passent