fix Uncaught exception in reduce.algo2/algo2_golden_tests.ts
  reduce.algo2/ccsf.ts(21,7): error TS2769: No overload matches this call.
    Overload 1 of 3, '(callbackfn: (previousValue: string, currentValue: string, currentIndex: number, array: string[]) => string, initialValue: string): string', gave the following error.
      Argument of type '(accu: { date_traitement: Date; }, hash: string) => { date_traitement: Date; } | undefined' is not assignable to parameter of type '(previousValue: string, currentValue: string, currentIndex: number, array: string[]) => string'.
        Types of parameters 'accu' and 'previousValue' are incompatible.
          Type 'string' is not assignable to type '{ date_traitement: Date; }'.
    Overload 2 of 3, '(callbackfn: (previousValue: { date_traitement: Date; }, currentValue: string, currentIndex: number, array: string[]) => { date_traitement: Date; }, initialValue: { date_traitement: Date; }): { ...; }', gave the following error.
      Argument of type '(accu: { date_traitement: Date; }, hash: string) => { date_traitement: Date; } | undefined' is not assignable to parameter of type '(previousValue: { date_traitement: Date; }, currentValue: string, currentIndex: number, array: string[]) => { date_traitement: Date; }'.
        Type '{ date_traitement: Date; } | undefined' is not assignable to type '{ date_traitement: Date; }'.
          Type 'undefined' is not assignable to type '{ date_traitement: Date; }'.
  reduce.algo2/ccsf.ts(24,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/ccsf.ts(25,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/ccsf.ts(36,17): error TS2339: Property 'date_traitement' does not exist on type 'string'.
  reduce.algo2/ccsf.ts(37,31): error TS2339: Property 'date_traitement' does not exist on type 'string'.