fix Uncaught exception in reduce.algo2/algo2_golden_tests.ts   reduce.algo2/lookAhead.ts(29,11): error TS2532: Object is possibly 'undefined'.   reduce.algo2/lookAhead.ts(36,9): error TS2322: Type 'Outcome | {}' is not assignable to type 'Outcome'.     Type '{}' is missing the following properties from type 'Outcome': time_til_outcome, outcome   reduce.algo2/lookAhead.ts(37,9): error TS2532: Object is possibly 'undefined'.  reduce.algo2/lookAhead.ts(38,13): error TS2532: Object is possibly 'undefined'.   reduce.algo2/lookAhead.ts(39,11): error TS2532: Object is possibly 'undefined'.   reduce.algo2/lookAhead.ts(41,11): error TS2532: Object is possibly 'undefined'.