fix Uncaught exception in reduce.algo2/algo2_golden_tests.ts
  reduce.algo2/cotisation.ts(41,29): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisation.ts(54,31): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisation.ts(55,30): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisation.ts(56,30): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisation.ts(60,13): error TS2339: Property 'cotisations' does not exist on type '{ cotisations: (number | undefined)[]; montantsPP: number[]; montantsPO: number[]; } | undefined'.
  reduce.algo2/cotisation.ts(60,26): error TS2339: Property 'montantsPO' does not exist on type '{ cotisations: (number | undefined)[]; montantsPP: number[]; montantsPO: number[]; } | undefined'.
  reduce.algo2/cotisation.ts(60,38): error TS2339: Property 'montantsPP' does not exist on type '{ cotisations: (number | undefined)[]; montantsPP: number[]; montantsPO: number[]; } | undefined'.
  reduce.algo2/cotisation.ts(61,18): error TS2322: Type 'SortieCotisation | {}' is not assignable to type 'SortieCotisation'.
    Type '{}' is missing the following properties from type 'SortieCotisation': ratio_dette, tag_debit, tag_default
  reduce.algo2/cotisation.ts(63,11): error TS2339: Property 'cotisation_moy12m' does not exist on type '{}'.
  reduce.algo2/cotisation.ts(65,20): error TS2339: Property 'cotisation_moy12m' does not exist on type '{}'.
  reduce.algo2/cotisation.ts(66,18): error TS2339: Property 'cotisation_moy12m' does not exist on type '{}'.
  reduce.algo2/cotisation.ts(67,20): error TS2339: Property 'cotisation_moy12m' does not exist on type '{}'.
  reduce.algo2/cotisation.ts(68,11): error TS2339: Property 'ratio_dette' does not exist on type '{}'.
  reduce.algo2/cotisation.ts(69,11): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisation.ts(70,12): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisation.ts(71,13): error TS2339: Property 'cotisation_moy12m' does not exist on type '{}'.
  reduce.algo2/cotisation.ts(73,13): error TS2339: Property 'ratio_dette_moy12m' does not exist on type '{}'.
  reduce.algo2/cotisation.ts(75,14): error TS7006: Parameter '_' implicitly has an 'any' type.
  reduce.algo2/cotisation.ts(75,17): error TS7006: Parameter 'i' implicitly has an 'any' type.
  reduce.algo2/cotisation.ts(76,49): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisation.ts(92,15): error TS2339: Property 'ratio_dette' does not exist on type 'SortieCotisation | undefined'.
  reduce.algo2/cotisation.ts(95,9): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/cotisation.ts(99,27): error TS2532: Object is possibly 'undefined'.