fix(tests): Erreur lors du lancement de test-all.sh sans paramètre "--update" (#151)
Pour résoudre le comportement suivant:

```
$ ./test-all.sh

  ava ""
  Internal error
  TypeError: Expected pattern to be a non-empty string
```

(regression introduite dans https://github.com/signaux-faibles/opensignauxfaibles/pull/149/files#diff-c81c8dfb64cb20f4ff8acb0df49b7614L30)