fix Uncaught exception in reduce.algo2/algo2_golden_tests.ts
  reduce.algo2/repeatable.ts(12,21): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/repeatable.ts(13,5): error TS2322: Type '{ random_order: number; } | {}' is not assignable to type '{ random_order: number; }'.
    Property 'random_order' is missing in type '{}' but required in type '{ random_order: number; }'.
  reduce.algo2/repeatable.ts(14,5): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/repeatable.ts(14,47): error TS2532: Object is possibly 'undefined'.