fix Uncaught exception in reduce.algo2/algo2_golden_tests.ts
  reduce.algo2/interim.ts(33,21): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/interim.ts(37,7): error TS2322: Type 'SortieInterim | {}' is not assignable to type 'SortieInterim'.
    Type '{}' is missing the following properties from type 'SortieInterim': interim_proportion, interim_ratio_past_6, interim_ratio_past_12, interim_ratio_past_18, interim_ratio_past_24
  reduce.algo2/interim.ts(38,15): error TS2339: Property 'effectif' does not exist on type 'Input | undefined'.
  reduce.algo2/interim.ts(40,9): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/interim.ts(40,54): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/interim.ts(46,47): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/interim.ts(51,9): error TS2322: Type 'SortieInterim | {}' is not assignable to type 'SortieInterim'.
    Type '{}' is missing the following properties from type 'SortieInterim': interim_proportion, interim_ratio_past_6, interim_ratio_past_12, interim_ratio_past_18, interim_ratio_past_24
  reduce.algo2/interim.ts(54,17): error TS2339: Property 'effectif' does not exist on type 'Input | undefined'.
  reduce.algo2/interim.ts(57,47): error TS2532: Object is possibly 'undefined'.