fix(JS): Validation des paramètres attendus par les fonctions map-reduce (#345)
Reprise de PR #55.

## Problème

Si un paramètre requis par un traitement map-reduce (implémenté en JavaScript/TypeScript, dans le répertoire `js`) n'est pas transmis à MongoDB par `sfdata` (implémenté à Go), une erreur d'exécution JavaScript pourrait (ou pas) être rapportée par MongoDB et faire échouer le traitement, potentiellement après des heures de calcul. (cf section "Comportement observé avant cette PR", plus bas)

## Approche proposée dans cette PR

- Faire en sorte que chaque traitement map-reduce empaqueté dans `jsFunctions.go` soit retourné par une fonction qui vérifie la présence de tous les paramètres requis par ce traitement.
- Appel au script de détection de variables globales invoqué dans `generate-javascript.sh` (employées pour transmettre les paramètres de fonctions map-reduce) pour générer les vérifications correspondantes dans `jsFunctions.go`.

Exemple: https://github.com/signaux-faibles/opensignauxfaibles/pull/345/files#diff-26ae22526dc3cc4029b73a80515d7b95f87aec0ff7882332db44208ce81afc36R359

## Comment reproduire/tester

Retirer un paramètre requis (ex: `"completeTypes": completeTypes,` de `lib/engine/data.go`) puis lancer les tests avec `$ make test`.

### Comportement observé avant cette PR

- `go test` ne rapporte pas l'erreur
- `test/test-compact.sh` rapporte l'erreur au milieu de l'exécution du map-reduce par MongoDB:

```
  💎 Compacting RawData...
    [sfdata] 2021/04/13 17:28:38 map[]
  - sfdata compact 👉 
  Erreur: ReferenceError: completeTypes is not defined :
  compactBatch@:10:11
  reduce/<@:74:36
  reduce@:69:5
  2021-04-13T15:28:38.615+0000 E  QUERY    [conn3] uncaught exception: ReferenceError: completeTypes is not defined :
```

### Comportement apporté par cette PR


- `make test` échoue rapidement avec le message d'erreur suivant:

```
Erreur: missing required parameter: completeTypes
[...]
--- FAIL: TestMain (5.20s)
    main_test.go:66: 
                Error Trace:    main_test.go:66
                Error:          Not equal: 
                                expected: 0
                                actual  : 3
                Test:           TestMain
FAIL
FAIL    github.com/signaux-faibles/opensignauxfaibles   5.218s
FAIL
```

- ainsi que `tests/test-compact.sh`, avant le lancement du map-reduce sur MongoDB:

```
  💎 Compacting RawData...
- sfdata compact 👉 
Erreur: missing required parameter: completeTypes
```

## Autres apports de la PR

- Codacy rapporte [24 points de réduction de code dupliqué](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/pullRequest?prid=7241813).
- 🧹 Retrait des paramètres obsolètes, dans le code de lancement des traitements map-reduce.
- Transformation en TypeScript du dernier traitement qui était encore implémenté en JavaScript: `purgeBatch`.
- Extraction d'une fonction `makeMapReduceJob()` pour dé-dupliquer le code de création de requête map-reduce à partir des fonctions de `jsFunctions.go`.
- Déplacement des fonctions de transpilation TypeScript->JavaScript vers `lib/engine/js/loadJS.go`, pour retirer la dépendance au package `engine` et donc de permettre la regénération de `jsFunctions.go` même si sa version actuelle est invalide. (erreurs de syntaxe)
- Formatage systématique du code de `jsFunctions.go`.
- Suppression de `GenereSeriePeriodeAnnuelle()`, non utilisée.
- Appeler `naf.LoadNAF()` à la demande, au lieu de le charger systématiquement au démarrage.