fix Uncaught exception in reduce.algo2/algo2_golden_tests.ts
  reduce.algo2/compte.ts(11,30): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/compte.ts(12,5): error TS2322: Type '{ compte_urssaf: unknown; } | {}' is not assignable to type '{ compte_urssaf: unknown; }'.
    Property 'compte_urssaf' is missing in type '{}' but required in type '{ compte_urssaf: unknown; }'.
  reduce.algo2/compte.ts(13,5): error TS2532: Object is possibly 'undefined'.
  reduce.algo2/compte.ts(13,44): error TS2532: Object is possibly 'undefined'.