fix Uncaught exception in compact/ava_tests.ts
  compact/ava_tests.ts(26,12): error TS2532: Object is possibly 'undefined'.
  compact/ava_tests.ts(100,48): error TS2322: Type '{ batch: Record<string, Partial<BatchValueProps>>; key: string; scope: "etablissement"; } | undefined' is not assignable to type 'CompanyDataValues'.
    Type 'undefined' is not assignable to type 'CompanyDataValues'.
  compact/ava_tests.ts(111,13): error TS2339: Property 'reporder' does not exist on type 'Partial<BatchValueProps> | undefined'.